# Generated by Django 6.1.1 on 2026-09-30 20:49

import compiler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Snippet",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=compiler.models.short_id,
                        editable=False,
                        max_length=16,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="название"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("typescript", "TypeScript"),
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                            ("kotlin", "Kotlin"),
                            ("ruby", "Ruby"),
                            ("php", "PHP"),
                            ("perl", "Perl"),
                            ("lua", "Lua"),
                            ("bash", "Bash"),
                            ("haskell", "Haskell"),
                            ("swift", "Swift"),
                            ("r", "R"),
                            ("dart", "Dart"),
                            ("elixir", "Elixir"),
                            ("sql", "SQL"),
                        ],
                        max_length=32,
                        verbose_name="язык",
                    ),
                ),
                ("code", models.TextField(verbose_name="код")),
                ("stdin", models.TextField(blank=True, verbose_name="ввод")),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="просмотры"),
                ),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="создан"),
                ),
            ],
            options={
                "verbose_name": "сниппет",
                "verbose_name_plural": "сниппеты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Execution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("javascript", "JavaScript"),
                            ("typescript", "TypeScript"),
                            ("c", "C"),
                            ("cpp", "C++"),
                            ("java", "Java"),
                            ("csharp", "C#"),
                            ("go", "Go"),
                            ("rust", "Rust"),
                            ("kotlin", "Kotlin"),
                            ("ruby", "Ruby"),
                            ("php", "PHP"),
                            ("perl", "Perl"),
                            ("lua", "Lua"),
                            ("bash", "Bash"),
                            ("haskell", "Haskell"),
                            ("swift", "Swift"),
                            ("r", "R"),
                            ("dart", "Dart"),
                            ("elixir", "Elixir"),
                            ("sql", "SQL"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="язык",
                    ),
                ),
                ("code", models.TextField(verbose_name="код")),
                ("stdin", models.TextField(blank=True, verbose_name="ввод")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ok", "Успешно"),
                            ("compile_error", "Ошибка компиляции"),
                            ("runtime_error", "Ошибка выполнения"),
                            ("timeout", "Превышено время"),
                            ("memory_limit", "Превышена память"),
                            ("output_limit", "Слишком много вывода"),
                            ("unavailable", "Недоступно"),
                            ("internal_error", "Внутренняя ошибка"),
                        ],
                        db_index=True,
                        max_length=32,
                        verbose_name="статус",
                    ),
                ),
                ("stdout", models.TextField(blank=True)),
                ("stderr", models.TextField(blank=True)),
                ("compile_output", models.TextField(blank=True)),
                ("message", models.CharField(blank=True, max_length=500)),
                ("exit_code", models.BigIntegerField(blank=True, null=True)),
                (
                    "time_ms",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="время, мс"
                    ),
                ),
                (
                    "memory_kb",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="память, КБ"
                    ),
                ),
                ("backend", models.CharField(blank=True, max_length=16)),
                ("truncated", models.BooleanField(default=False)),
                (
                    "session_key",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("client_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="запущен"
                    ),
                ),
            ],
            options={
                "verbose_name": "запуск",
                "verbose_name_plural": "запуски",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_key", "-created_at"],
                        name="compiler_ex_session_178543_idx",
                    )
                ],
            },
        ),
    ]
