# Generated by Django 6.1.1 on 2026-09-30 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="files",
            field=models.JSONField(blank=True, default=list, verbose_name="файлы"),
        ),
        migrations.AddField(
            model_name="snippet",
            name="files",
            field=models.JSONField(blank=True, default=list, verbose_name="файлы"),
        ),
    ]
