# Generated by Django 6.1.1 on 2026-09-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0002_project_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="execution",
            name="status",
            field=models.CharField(
                choices=[
                    ("ok", "Успешно"),
                    ("compile_error", "Ошибка компиляции"),
                    ("runtime_error", "Ошибка выполнения"),
                    ("timeout", "Превышено время"),
                    ("memory_limit", "Превышена память"),
                    ("output_limit", "Слишком много вывода"),
                    ("stopped", "Остановлено"),
                    ("unavailable", "Недоступно"),
                    ("internal_error", "Внутренняя ошибка"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="статус",
            ),
        ),
    ]
