# Generated by Django 6.1.1 on 2026-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0003_stopped_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="args",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="аргументы"
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="args",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="аргументы"
            ),
        ),
    ]
