# Generated by Django 6.1.1 on 2026-10-01 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0004_args"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="execution",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="forked_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forks",
                to="compiler.snippet",
                verbose_name="форк от",
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snippets",
                to=settings.AUTH_USER_MODEL,
                verbose_name="владелец",
            ),
        ),
        migrations.AddField(
            model_name="snippet",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="изменён"),
        ),
        migrations.AddIndex(
            model_name="snippet",
            index=models.Index(
                fields=["owner", "-updated_at"], name="compiler_sn_owner_i_ac71f3_idx"
            ),
        ),
    ]
