# Generated by Django 6.1.1 on 2026-10-01 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compiler", "0005_accounts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="snippet",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Публичный"),
                    ("unlisted", "По ссылке"),
                    ("private", "Приватный"),
                ],
                db_index=True,
                default="unlisted",
                max_length=16,
                verbose_name="видимость",
            ),
        ),
        migrations.AlterField(
            model_name="execution",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("typescript", "TypeScript"),
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("java", "Java"),
                    ("csharp", "C#"),
                    ("go", "Go"),
                    ("rust", "Rust"),
                    ("kotlin", "Kotlin"),
                    ("ruby", "Ruby"),
                    ("php", "PHP"),
                    ("perl", "Perl"),
                    ("lua", "Lua"),
                    ("bash", "Bash"),
                    ("haskell", "Haskell"),
                    ("swift", "Swift"),
                    ("r", "R"),
                    ("dart", "Dart"),
                    ("elixir", "Elixir"),
                    ("sql", "SQL"),
                    ("pascal", "Pascal"),
                    ("fortran", "Fortran"),
                    ("assembly", "Assembly"),
                    ("prolog", "Prolog"),
                    ("vbnet", "Visual Basic .NET"),
                    ("objc", "Objective-C"),
                    ("scala", "Scala"),
                    ("fsharp", "F#"),
                    ("ocaml", "OCaml"),
                    ("erlang", "Erlang"),
                    ("clojure", "Clojure"),
                    ("julia", "Julia"),
                    ("zig", "Zig"),
                    ("nim", "Nim"),
                    ("crystal", "Crystal"),
                    ("d", "D"),
                    ("cobol", "COBOL"),
                    ("ada", "Ada"),
                    ("commonlisp", "Common Lisp"),
                    ("groovy", "Groovy"),
                ],
                db_index=True,
                max_length=32,
                verbose_name="язык",
            ),
        ),
        migrations.AlterField(
            model_name="snippet",
            name="language",
            field=models.CharField(
                choices=[
                    ("python", "Python"),
                    ("javascript", "JavaScript"),
                    ("typescript", "TypeScript"),
                    ("c", "C"),
                    ("cpp", "C++"),
                    ("java", "Java"),
                    ("csharp", "C#"),
                    ("go", "Go"),
                    ("rust", "Rust"),
                    ("kotlin", "Kotlin"),
                    ("ruby", "Ruby"),
                    ("php", "PHP"),
                    ("perl", "Perl"),
                    ("lua", "Lua"),
                    ("bash", "Bash"),
                    ("haskell", "Haskell"),
                    ("swift", "Swift"),
                    ("r", "R"),
                    ("dart", "Dart"),
                    ("elixir", "Elixir"),
                    ("sql", "SQL"),
                    ("pascal", "Pascal"),
                    ("fortran", "Fortran"),
                    ("assembly", "Assembly"),
                    ("prolog", "Prolog"),
                    ("vbnet", "Visual Basic .NET"),
                    ("objc", "Objective-C"),
                    ("scala", "Scala"),
                    ("fsharp", "F#"),
                    ("ocaml", "OCaml"),
                    ("erlang", "Erlang"),
                    ("clojure", "Clojure"),
                    ("julia", "Julia"),
                    ("zig", "Zig"),
                    ("nim", "Nim"),
                    ("crystal", "Crystal"),
                    ("d", "D"),
                    ("cobol", "COBOL"),
                    ("ada", "Ada"),
                    ("commonlisp", "Common Lisp"),
                    ("groovy", "Groovy"),
                ],
                max_length=32,
                verbose_name="язык",
            ),
        ),
        migrations.CreateModel(
            name="SocialAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("github", "GitHub"), ("google", "Google")],
                        max_length=16,
                    ),
                ),
                (
                    "uid",
                    models.CharField(max_length=255, verbose_name="id у провайдера"),
                ),
                (
                    "login",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="логин / почта у провайдера",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "внешний аккаунт",
                "verbose_name_plural": "внешние аккаунты",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "uid"), name="unique_social_account"
                    )
                ],
            },
        ),
    ]
